// Build every engine from its measurements.
//
//   node tools/build-engines.js          write engines/v4.js ... v12.js and engines/index.js
//   node tools/build-engines.js --check  write nothing; exit 1 if any file is out of date
//
// The files it writes are committed and never edited by hand. test/engines.test.js runs the
// same build in memory and fails if a committed file differs from what the parameters give.

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { ENGINES, SHARED } from '../engines/params.js';
import { buildEngine } from './engine-maths.js';

const DIR = fileURLToPath(new URL('../engines/', import.meta.url));

// JSON, but with lists of numbers wrapped into lines rather than one number per line, so a
// generated file is a few dozen lines a table and can still be read.
function serialise(value, indent = '') {
  const inner = indent + '  ';
  if (Array.isArray(value)) {
    if (value.every((v) => typeof v === 'number')) {
      const lines = [];
      let line = '';
      for (const v of value) {
        const item = `${v}, `;
        if (line.length + item.length > 92) {
          lines.push(line.trimEnd());
          line = '';
        }
        line += item;
      }
      if (line) lines.push(line.trimEnd());
      return `[\n${lines.map((l) => inner + l).join('\n')}\n${indent}]`;
    }
    return `[\n${value.map((v) => inner + serialise(v, inner)).join(',\n')}\n${indent}]`;
  }
  if (value && typeof value === 'object') {
    const entries = Object.entries(value).map(([k, v]) => `${inner}${k}: ${serialise(v, inner)}`);
    return `{\n${entries.join(',\n')},\n${indent}}`;
  }
  return JSON.stringify(value);
}

export function engineFile(params, shared) {
  const hash = createHash('sha256').update(JSON.stringify({ shared, params })).digest('hex');
  return [
    '// Generated by tools/build-engines.js from engines/params.js. Do not edit: change the',
    '// parameters and run `node tools/build-engines.js`.',
    `// parameters sha256 ${hash}`,
    '',
    `export default ${serialise(buildEngine(params, shared))};`,
    '',
  ].join('\n');
}

export function indexFile(engines) {
  return [
    '// Generated by tools/build-engines.js. The engines in the order the page cycles them.',
    '',
    ...engines.map((e) => `import ${e.id} from './${e.id}.js';`),
    '',
    `export const ENGINES = [${engines.map((e) => e.id).join(', ')}];`,
    '',
  ].join('\n');
}

export function expectedFiles() {
  const files = { 'index.js': indexFile(ENGINES) };
  for (const p of ENGINES) files[`${p.id}.js`] = engineFile(p, SHARED);
  return files;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes('--check');
  let stale = 0;
  for (const [name, text] of Object.entries(expectedFiles())) {
    let current = null;
    try {
      current = readFileSync(DIR + name, 'utf8');
    } catch {
      // Not written yet.
    }
    if (current === text) continue;
    stale += 1;
    if (check) console.error(`engines/${name} is out of date`);
    else {
      writeFileSync(DIR + name, text, 'utf8');
      console.error(`wrote engines/${name}`);
    }
  }
  if (!stale) console.error('every engine file is up to date');
  if (check && stale) process.exit(1);
}
