// Generated by tools/build-engines.js. The engines in the order the page cycles them.

import v4 from './v4.js';
import v6 from './v6.js';
import v8 from './v8.js';
import v10 from './v10.js';
import v12 from './v12.js';

export const ENGINES = [v4, v6, v8, v10, v12];
