"""The corpus reader: the ten documents, run and compared, inside the repository.

Every corpus figure quoted in `requirements/06-context.md` up to this point - "5 of 10",
"8 of 10", "9 of 10" - came from a script written for the occasion and thrown away. Three
separate sessions each wrote their own, and the one number that was never produced by a
script at all ("91 tests pass") is the one that turned out to be wrong. This module is that
script, kept.

It is deliberately not the stage 8 harness. The harness reports per-field accuracy across
thirty to forty documents and records a baseline; this asserts that ten known documents
still come out right, which is a regression test and belongs in `tests/`. When the harness
arrives it should read these same files and this can stay as the fast check.

Three things it does that the throwaway scripts did not:

**It compares every key in `expected`, not the ones a run happened to print.** `08-two-page`
was reported clean for a whole session with seven wrong line amounts in it, because the check
that ran compared `line_item_count: 40` and got 40.

**It refuses to skip a key it does not understand.** `has_negative_line`,
`issue_date_is_ambiguous` and `spans_pages` sat in the labels naming nothing on
`InvoiceFields`, so any comparison written against the extracted fields silently ignored
them - including the one that exists to prove `06-ambiguous-date` flags its date rather than
guessing, which was the entire reason that document is in the corpus. `_CHECKS` is the
closed set of keys that can be evaluated, and `test_every_expected_key_is_checkable` fails on
anything outside it. Adding a label now means saying how it is measured.

**It adds each document up.** Quantity times unit price against the line amount, the line
amounts against the printed subtotal, and subtotal plus tax against the total. This needs no
labels at all, which is why it is the strongest check here: it found the date-mask bug and
`02-many-lines`' self-contradicting ground truth in one pass, on a corpus of any size, and it
is the only thing that would catch a line item silently dropped before it was ever read.
"""

from __future__ import annotations

import io
import json
from decimal import Decimal
from pathlib import Path
from typing import Any

import pdfplumber
import pytest

from mailman.corpus import CASES, Case
from mailman.extractor import ExtractionError
from mailman.heuristic import HeuristicExtractor
from mailman.invoice import InvoiceFields

CORPUS_DIR = Path(__file__).resolve().parent.parent / "corpus"

# `01-clean`'s buyer_name. The heuristic does not attempt a buyer and a guess would be worse
# than a null, so the corpus records the document's truth and this records that the deployed
# extractor does not reach it. Listed rather than deleted from the labels, because the label
# is right and the extractor is the thing that is short - and because this is the clearest
# case for the trained model earning its 250MB. Removing the entry is how that gets noticed.
KNOWN_GAPS = {("01-clean", "buyer_name")}


def _text(case: Case) -> tuple[str, int]:
    """The document as the pipeline sees it: pdfplumber over the generated bytes."""
    with pdfplumber.open(io.BytesIO(case.pdf())) as document:
        pages = [page.extract_text() or "" for page in document.pages]
    return "\n".join(pages), len(pages)


def _extract(case: Case) -> tuple[InvoiceFields, int]:
    text, page_count = _text(case)
    return HeuristicExtractor().extract(text).fields, page_count


def _money(value: Any) -> Decimal | None:
    return None if value is None else Decimal(str(value))


# How each key in a case's `expected` block is turned into an actual value. Anything not in
# here is a label nobody has said how to measure, and the test below fails on it rather than
# passing over it.
_CHECKS: dict[str, Any] = {
    # Plain fields, compared as strings.
    "invoice_number": lambda f, pages: f.invoice_number,
    "vendor_name": lambda f, pages: f.vendor_name,
    "buyer_name": lambda f, pages: f.buyer_name,
    "currency": lambda f, pages: f.currency,
    # Dates, compared in ISO form so the label reads like the document's answer.
    "issue_date": lambda f, pages: f.issue_date.isoformat() if f.issue_date else None,
    "due_date": lambda f, pages: f.due_date.isoformat() if f.due_date else None,
    # Amounts, compared numerically. "270.40" and Decimal("270.4") are the same answer and a
    # string comparison would call one of them wrong.
    "subtotal": lambda f, pages: f.subtotal,
    "tax": lambda f, pages: f.tax,
    "total": lambda f, pages: f.total,
    # Line items, handled separately below because the comparison is per line per field.
    "line_items": lambda f, pages: f.line_items,
    "line_item_count": lambda f, pages: len(f.line_items),
    # The three that used to be unevaluable. Each now names something real.
    "has_negative_line": lambda f, pages: any(
        item["amount"] is not None and item["amount"] < 0 for item in f.line_items
    ),
    "issue_date_is_ambiguous": lambda f, pages: "issue_date" in f.ambiguous_dates,
    "spans_pages": lambda f, pages: pages > 1,
}

_MONEY_KEYS = {"subtotal", "tax", "total"}
_LINE_MONEY_KEYS = {"quantity", "unit_price", "amount"}

EXTRACTING = [case for case in CASES if not case.should_fail]
REFUSING = [case for case in CASES if case.should_fail]


def _ids(cases: list[Case]) -> list[str]:
    return [case.name for case in cases]


def test_every_expected_key_is_checkable() -> None:
    """A label that cannot be evaluated is not an assertion.

    This is the guard the corpus went three sessions without. `06-ambiguous-date` exists to
    prove the parser flags `03/04/2026` instead of quietly picking a reading, and its only
    statement of that was a key no comparison knew what to do with, on a case that carries no
    `issue_date` label either. It could not fail on its own subject.
    """
    unknown = sorted(
        f"{case.name}.{key}"
        for case in CASES
        for key in case.expected
        if key not in _CHECKS
    )
    assert not unknown, (
        "expected keys with no entry in _CHECKS: " + ", ".join(unknown) + ". "
        "Add the key to _CHECKS with how it is measured, or take it out of the label - "
        "a key nothing evaluates reads as a passing assertion."
    )


@pytest.mark.parametrize("case", EXTRACTING, ids=_ids(EXTRACTING))
def test_case_extracts_every_expected_field(case: Case) -> None:
    """Compare every key in `expected`, not the ones a run happens to print."""
    fields, page_count = _extract(case)

    wrong: list[str] = []
    for key, expected in case.expected.items():
        if (case.name, key) in KNOWN_GAPS:
            continue
        if key == "line_items":
            wrong.extend(_line_item_problems(expected, fields.line_items))
            continue

        actual = _CHECKS[key](fields, page_count)
        if key in _MONEY_KEYS:
            if _money(expected) != _money(actual):
                wrong.append(f"{key}: expected {expected!r}, got {actual!r}")
        elif expected != actual:
            wrong.append(f"{key}: expected {expected!r}, got {actual!r}")

    assert not wrong, f"{case.name} ({case.tests})\n  " + "\n  ".join(wrong)


def _line_item_problems(expected: list[dict], actual: list[dict]) -> list[str]:
    """Per line, per field. A length check alone is `line_item_count` wearing a disguise."""
    if len(expected) != len(actual):
        return [
            f"line_items: expected {len(expected)} lines, got {len(actual)}: "
            + ", ".join(repr(item["description"]) for item in actual)
        ]

    problems: list[str] = []
    for index, (want, got) in enumerate(zip(expected, actual)):
        for key, value in want.items():
            found = got.get(key)
            same = (
                _money(value) == _money(found)
                if key in _LINE_MONEY_KEYS
                else value == found
            )
            if not same:
                problems.append(f"line[{index}].{key}: expected {value!r}, got {found!r}")
    return problems


@pytest.mark.parametrize("case", EXTRACTING, ids=_ids(EXTRACTING))
def test_case_adds_up(case: Case) -> None:
    """Each document against its own arithmetic. No labels involved.

    This is the check that needs nothing to be right about the answer key, so it survives a
    label that is wrong and a document that contradicts itself. Both of those have happened
    here, and this is what found them.
    """
    fields, _ = _extract(case)
    lines = fields.line_items
    subtotal, tax, total = fields.subtotal, fields.tax, fields.total

    wrong: list[str] = []

    for item in lines:
        quantity, unit_price, amount = (
            item["quantity"],
            item["unit_price"],
            item["amount"],
        )
        if None not in (quantity, unit_price, amount) and quantity * unit_price != amount:
            wrong.append(
                f"line[{item['line_no']}] {item['description']!r}: "
                f"{quantity} x {unit_price} = {quantity * unit_price}, printed {amount}"
            )

    if lines and subtotal is not None:
        summed = sum((item["amount"] for item in lines if item["amount"] is not None), Decimal(0))
        if summed != subtotal:
            wrong.append(
                f"{len(lines)} line items sum to {summed}, subtotal says {subtotal} "
                f"(difference {subtotal - summed}) - a line is missing, invented or misread"
            )

    if None not in (subtotal, tax, total) and subtotal + tax != total:
        wrong.append(f"subtotal {subtotal} + tax {tax} = {subtotal + tax}, total says {total}")

    assert not wrong, f"{case.name} ({case.tests})\n  " + "\n  ".join(wrong)


@pytest.mark.parametrize("case", REFUSING, ids=_ids(REFUSING))
def test_case_is_refused(case: Case) -> None:
    """A corpus of documents that should all succeed cannot measure refusal.

    The `expected` block on a refusing case says which fields are absent, and those are
    checked against the read carried on the error rather than discarded - a refusal that
    happened for the wrong reason is not the behaviour being asserted.
    """
    text, _ = _text(case)

    with pytest.raises(ExtractionError) as raised:
        HeuristicExtractor().extract(text)

    read = raised.value.raw["read"]
    still_found = {
        key: read.get(key)
        for key, value in case.expected.items()
        if value is None and read.get(key) is not None
    }
    assert not still_found, (
        f"{case.name} was refused, but it still produced {still_found} - "
        "the label says those fields are not in the document"
    )


@pytest.mark.parametrize("case", CASES, ids=_ids(CASES))
def test_files_on_disk_match_the_generator(case: Case) -> None:
    """`corpus/` is a build artefact of `corpus.py`, and a stale one is invisible.

    Everything above runs against freshly generated bytes, so a corpus directory that has
    drifted would never show up there - and the labels beside those PDFs are what the stage 8
    harness will read. Both halves are compared, because regenerating a PDF without its
    labels, or the reverse, is the shape a hand-edited answer key takes.
    """
    pdf_path = CORPUS_DIR / f"{case.name}.pdf"
    labels_path = CORPUS_DIR / f"{case.name}.labels.json"

    if not pdf_path.exists() or not labels_path.exists():
        pytest.skip(f"{case.name} not written to {CORPUS_DIR}; run python -m mailman.corpus")

    assert pdf_path.read_bytes() == case.pdf(), (
        f"{pdf_path.name} differs from what corpus.py produces - regenerate with "
        "python -m mailman.corpus"
    )

    on_disk = json.loads(labels_path.read_text(encoding="utf-8"))
    assert on_disk["expected"] == json.loads(json.dumps(case.expected)), (
        f"{labels_path.name} differs from the expected block in corpus.py - regenerate with "
        "python -m mailman.corpus"
    )
    assert on_disk["should_fail"] == case.should_fail
