"""Stage 6: a checkpoint. Did the pack that was served actually carry what it claims to?

One checkpoint hangs off one injection, because a score has to refer to the exact text that
was sent. The steps:

    1. targets    entries the version included, entries it excluded, user messages no entry
                  claims - chosen by `domain.integrity.select_probes`
    2. probes     cached per (entry, revision, category); generated by the local model on a miss
    3. answers    the injection's own pack text plus one question, per probe
    4. grades     NLI in both directions, `domain.integrity.grade`
    5. score      the weighted mean; nothing graded means no checkpoint, never a made-up one
    6. effects    `transmission_failed` on included zeroes, a suggestion for every other zero

The pure decisions all live in `domain/integrity.py`. This module is the plumbing around them
and should contain no judgement worth arguing about.
"""

from __future__ import annotations

import asyncio
import logging
import time
import uuid
from dataclasses import dataclass, field

from sqlalchemy import func, select, update
from sqlalchemy.ext.asyncio import AsyncSession

from herder.core.ids import uuid7
from herder.core.modelcalls import record_call
from herder.domain.integrity import (
    CATEGORIES,
    EXCLUDED,
    INCLUDED,
    UNCOVERED,
    GradedProbe,
    ProbeTarget,
    grade,
    leaks_answer,
    score,
    select_probes,
)
from herder.domain.merge import ENTAILMENT
from herder.domain.render import TAIL_KIND
from herder.models import (
    BriefVersion,
    Checkpoint,
    Conversation,
    Entry,
    EntryLineage,
    EntryRevision,
    Injection,
    Message,
    Probe,
    ProbeResult,
    Project,
    Suggestion,
)

log = logging.getLogger("herder.checkpoint")

# A raw message shorter than this is almost never a fact - "ok", "thanks, go on". Probing one
# spends a model call to learn that it contained nothing.
MIN_UNCOVERED_TOKENS = 8
UNCOVERED_POOL_LIMIT = 2000


class CheckpointError(ValueError):
    """The checkpoint could not produce a score. Recorded as a failure, never as a number."""


@dataclass
class ProbeReport:
    category: str
    question: str
    expected_answer: str
    answer: str
    score: float | None
    reason: str
    entry_id: uuid.UUID | None = None
    message_id: uuid.UUID | None = None


@dataclass
class CheckpointRun:
    injection_id: uuid.UUID
    checkpoint_id: uuid.UUID | None = None
    integrity: float | None = None
    by_category: dict[str, tuple[float | None, int]] = field(default_factory=dict)
    requested: dict[str, int] = field(default_factory=dict)
    available: dict[str, int] = field(default_factory=dict)
    selected: int = 0
    probes_cached: int = 0
    probes_generated: int = 0
    probes_missing: int = 0
    graded: int = 0
    inconclusive: int = 0
    unanswered: int = 0
    transmission_failed: int = 0
    suggestions: int = 0
    latency_ms: int = 0
    reports: list[ProbeReport] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)


def _flat(text: str) -> str:
    return " ".join(text.split())


# ------------------------------------------------------------------------ targets


async def _targets(
    session: AsyncSession, project: Project, version: BriefVersion
) -> tuple[list[ProbeTarget], list[ProbeTarget], list[ProbeTarget]]:
    ids = list(version.included_entry_ids) + list(version.excluded_entry_ids)
    entries = {
        e.id: e
        for e in (
            await session.execute(select(Entry).where(Entry.id.in_(ids), Entry.kind != TAIL_KIND))
        ).scalars()
    } if ids else {}

    included = [
        ProbeTarget(INCLUDED, entry_id=i, pinned=entries[i].status == "pinned")
        for i in version.included_entry_ids
        if i in entries
    ]
    # Only entries still live. "Add this back" is the suggestion an excluded zero produces, and
    # suggesting the user add back an entry they have since removed would be arguing with them.
    excluded = [
        ProbeTarget(EXCLUDED, entry_id=i)
        for i in version.excluded_entry_ids
        if i in entries and entries[i].status in ("active", "pinned")
    ]

    claimed = (
        select(EntryLineage.message_id)
        .join(Entry, Entry.id == EntryLineage.entry_id)
        .where(Entry.project_id == project.id)
    )
    rows = (
        await session.execute(
            select(Message.id, Message.content)
            .join(Conversation, Conversation.id == Message.conversation_id)
            .where(
                Conversation.project_id == project.id,
                # Extraction only ever keeps what the user said, so only the user's turns can
                # be something it missed.
                Message.role == "user",
                Message.token_count >= MIN_UNCOVERED_TOKENS,
                Message.created_at <= version.created_at,
                # Claimed by ANY entry, removed ones included: an entry the user removed covered
                # this message, and "extract this" would resurrect it by suggestion.
                Message.id.not_in(claimed),
            )
            .order_by(Message.created_at.desc())
            .limit(UNCOVERED_POOL_LIMIT)
        )
    ).all()
    # A message the pack carries verbatim - in the session tail - is not something extraction
    # missed. Probing it would measure the tail and credit it to the wrong category.
    pack = _flat(version.rendered_text)
    uncovered = [ProbeTarget(UNCOVERED, message_id=mid) for mid, content in rows if _flat(content) not in pack]

    return included, excluded, uncovered


# ------------------------------------------------------------------------ probes


async def _revision_served(session: AsyncSession, entry_id: uuid.UUID, version: BriefVersion) -> EntryRevision | None:
    """The revision the version was rendered from, not whatever the entry says now.

    An entry edited after the serve would otherwise be probed on text the pack never held.
    """
    revision = (
        await session.execute(
            select(func.max(EntryRevision.revision)).where(
                EntryRevision.entry_id == entry_id, EntryRevision.created_at <= version.created_at
            )
        )
    ).scalar_one_or_none()
    if revision is None:
        return None
    return await session.get(EntryRevision, (entry_id, revision))


async def _probe_for(
    session: AsyncSession,
    project: Project,
    version: BriefVersion,
    target: ProbeTarget,
    generator,
    nli,
    floor: float,
    run: CheckpointRun,
) -> Probe | None:
    if target.entry_id is not None:
        entry = await session.get(Entry, target.entry_id)
        revision = await _revision_served(session, target.entry_id, version)
        if entry is None or revision is None:
            run.errors.append(f"no revision of entry {target.entry_id} predates the version")
            return None
        same = select(Probe).where(Probe.entry_id == entry.id, Probe.entry_revision == revision.revision)
        label = entry.kind
        title, body = revision.title.strip(), _flat(revision.text_)
        content = body if body.lower().startswith(title.lower()) else f"{title} - {body}"
    else:
        message = await session.get(Message, target.message_id)
        if message is None:
            return None
        same = select(Probe).where(Probe.message_id == message.id, Probe.entry_id.is_(None))
        label, content, revision = "message", message.content, None

    cached = (await session.execute(same.where(Probe.category == target.category).limit(1))).scalars().first()
    if cached is not None:
        run.probes_cached += 1
        return cached

    # The same entry revision probed under another category - included in one serve, excluded
    # from another. The question and answer do not depend on the category, so they are copied
    # rather than paid for twice.
    sibling = (await session.execute(same.limit(1))).scalars().first()
    if sibling is not None:
        question, expected = sibling.question, sibling.expected_answer
        run.probes_cached += 1
    else:
        outcome = await asyncio.to_thread(generator.generate, label, content)
        call = outcome.call
        await record_call(
            session,
            "probe_gen",
            model=call.model,
            implementation=generator.name,
            prompt_version=call.prompt_version,
            raw_output=call.content,
            error=call.error,
            input_tokens=call.input_tokens,
            output_tokens=call.output_tokens,
            latency_ms=call.latency_ms,
            load_ms=call.load_ms,
            prompt_ms=call.prompt_ms,
            generation_ms=call.generation_ms,
            validated_first_try=not call.failed,
        )
        spec = outcome.spec
        if call.failed or spec is None:
            # No probe for this target. The checkpoint runs with fewer and reports the count.
            run.probes_missing += 1
            run.errors.append(f"probe generation failed: {call.error}")
            return None
        if not spec.has_fact or not spec.question.strip() or not spec.expected_answer.strip():
            # Said, so an honest "could not be written" is not a silent one.
            run.probes_missing += 1
            run.errors.append(f"no checkable fact found in [{label}] {content[:60]!r}")
            return None
        if leaks_answer(spec.question, spec.expected_answer):
            run.probes_missing += 1
            run.errors.append(f"discarded a probe whose question gives away its answer: {spec.question!r}")
            return None

        # "Do not invent", enforced in code rather than hoped for - the same reason lineage is
        # checked against the chunk. The first real run wrote "Preference lengths are stored as
        # integers" for "I prefer short answers with no preamble". An invented expected answer
        # is a guaranteed zero that flags a good entry as failing to transmit.
        [grounding] = nli.classify([(content, spec.expected_answer)])
        grounded = grounding.label == ENTAILMENT and grounding.score >= floor
        await record_call(
            session,
            "probe_check",
            model=nli.model_name,
            implementation=nli.name,
            raw_output=f"{grounding.label} {grounding.score:.2f}",
            latency_ms=getattr(nli, "last_latency_ms", None),
            validated_first_try=grounded,
        )
        if not grounded:
            run.probes_missing += 1
            run.errors.append(
                f"discarded a probe the content does not support ({grounding.label} "
                f"{grounding.score:.2f}): {spec.expected_answer!r}"
            )
            return None
        question, expected = spec.question.strip(), spec.expected_answer.strip()
        run.probes_generated += 1

    probe = Probe(
        id=uuid7(),
        project_id=project.id,
        entry_id=target.entry_id,
        entry_revision=revision.revision if revision is not None else None,
        message_id=target.message_id,
        category=target.category,
        question=question,
        expected_answer=expected,
    )
    session.add(probe)
    await session.flush()
    return probe


# ------------------------------------------------------------------------ the run


async def run_checkpoint(
    session: AsyncSession,
    injection_id: uuid.UUID,
    generator,
    answerer,
    nli,
    *,
    floor: float,
    counts: dict[str, int] | None = None,
) -> CheckpointRun:
    started = time.perf_counter()
    run = CheckpointRun(injection_id=injection_id)

    injection = await session.get(Injection, injection_id)
    if injection is None:
        raise CheckpointError(f"no injection {injection_id}")
    version = await session.get(BriefVersion, injection.brief_version_id)
    project = await session.get(Project, version.project_id)

    included, excluded, uncovered = await _targets(session, project, version)
    selection = select_probes(included, excluded, uncovered, seed=str(injection.id), counts=counts)
    run.requested, run.available, run.selected = selection.requested, selection.available, len(selection.targets)
    if not selection.targets:
        raise CheckpointError(f"nothing to probe in {project.name} v{version.version}")

    probes: list[tuple[ProbeTarget, Probe]] = []
    for target in selection.targets:
        probe = await _probe_for(session, project, version, target, generator, nli, floor, run)
        if probe is not None:
            probes.append((target, probe))
    # Committed before answering, so probes paid for survive a failure further on.
    await session.commit()

    graded: list[GradedProbe] = []
    results: list[ProbeResult] = []
    for target, probe in probes:
        call = await asyncio.to_thread(answerer.answer, injection.pack_text, probe.question)
        await record_call(
            session,
            "answer",
            model=call.model,
            implementation=answerer.name,
            prompt_version=call.prompt_version,
            raw_output=call.content,
            error=call.error,
            input_tokens=call.input_tokens,
            output_tokens=call.output_tokens,
            latency_ms=call.latency_ms,
            load_ms=call.load_ms,
            prompt_ms=call.prompt_ms,
            generation_ms=call.generation_ms,
            validated_first_try=not call.failed,
        )

        if call.failed:
            value, reason = None, f"not graded: the answer call failed ({call.error})"
            run.unanswered += 1
        else:
            forward, backward = nli.classify(
                [(f"{probe.question} {call.content}", probe.expected_answer), (probe.expected_answer, call.content)]
            )
            outcome = grade(forward, backward, floor)
            value, reason = outcome.score, outcome.reason
            await record_call(
                session,
                "grade",
                model=nli.model_name,
                implementation=nli.name,
                raw_output=reason,
                latency_ms=getattr(nli, "last_latency_ms", None),
                validated_first_try=True,
            )

        graded.append(GradedProbe(target.category, value))
        results.append(ProbeResult(probe_id=probe.id, answer=call.content, score=value, judge_reason=reason))
        run.reports.append(
            ProbeReport(
                category=target.category,
                question=probe.question,
                expected_answer=probe.expected_answer,
                answer=call.content,
                score=value,
                reason=reason,
                entry_id=probe.entry_id,
                message_id=probe.message_id,
            )
        )

    summary = score(graded)
    run.integrity, run.by_category = summary.integrity, summary.by_category
    run.graded, run.inconclusive = summary.graded, summary.inconclusive - run.unanswered

    if summary.integrity is None:
        # The model calls are kept - they are the evidence of why - but no checkpoint row is
        # written. A score of 0 here would say the context failed to transmit, when what
        # actually happened is that nothing was measured.
        await session.commit()
        raise CheckpointError(
            f"no probe could be graded ({len(probes)} probes, {run.unanswered} unanswered, "
            f"{run.inconclusive} inconclusive, {run.probes_missing} could not be written)"
        )

    run.latency_ms = int((time.perf_counter() - started) * 1000)
    checkpoint = Checkpoint(
        id=uuid7(),
        injection_id=injection.id,
        mode="local",
        judge_model=nli.model_name,
        answer_model=answerer.model,
        integrity=summary.integrity,
        probe_count=summary.graded,
        latency_ms=run.latency_ms,
    )
    session.add(checkpoint)
    await session.flush()
    for result in results:
        result.checkpoint_id = checkpoint.id
        session.add(result)
    run.checkpoint_id = checkpoint.id

    await _apply_effects(session, project, run)
    await session.commit()

    log.info(
        "checkpoint %s on %s v%d: integrity %.2f over %d graded probes in %d ms",
        checkpoint.id, project.name, version.version, summary.integrity, summary.graded, run.latency_ms,
    )
    return run


async def _apply_effects(session: AsyncSession, project: Project, run: CheckpointRun) -> None:
    for report in run.reports:
        if report.category == INCLUDED and report.entry_id is not None:
            # Set on a zero, cleared on a full score: the flag answers "did this entry transmit
            # last time it was checked", and a later clean pass is the answer to that. A 0.5
            # changes nothing - it neither proves nor disproves transmission.
            if report.score in (0.0, 1.0):
                failed = report.score == 0.0
                await session.execute(update(Entry).where(Entry.id == report.entry_id).values(transmission_failed=failed))
                run.transmission_failed += int(failed)
            continue

        if report.score != 0.0:
            continue

        if report.category == EXCLUDED:
            kind, entry_id, message_id = "add_back", report.entry_id, None
            text = f"Left out of the brief by the budget, and the model could not answer: {report.question}"
        else:
            kind, entry_id, message_id = "extract", None, report.message_id
            text = f"Said in the conversation, in no entry, and the model could not answer: {report.question}"

        # One open suggestion per thing. Every checkpoint that probes the same miss would
        # otherwise stack another copy in the inbox.
        open_already = (
            await session.execute(
                select(Suggestion.id).where(
                    Suggestion.project_id == project.id,
                    Suggestion.kind == kind,
                    Suggestion.status == "open",
                    (Suggestion.entry_id == entry_id) if entry_id is not None else (Suggestion.message_id == message_id),
                ).limit(1)
            )
        ).first()
        if open_already is None:
            session.add(
                Suggestion(id=uuid7(), project_id=project.id, kind=kind, entry_id=entry_id, message_id=message_id, text_=text)
            )
            run.suggestions += 1

    await session.flush()


# Kept importable for the API and CLI, which report the same three categories.
__all__ = ["CATEGORIES", "CheckpointError", "CheckpointRun", "ProbeReport", "run_checkpoint"]
