"""The eighteen tables.

Revision ID: 0001_initial
Revises:
Create Date: stage 0

Hand-written rather than autogenerated, on purpose. The constraints in here are the design:
the two unique constraints on `messages` are what make ingest idempotent and ordered, the
partial unique index on `jobs` is what stops two derives racing for one project, and the
check constraints are the vocabularies from requirements/04-data-model.md written where the
database can enforce them. Autogenerate would have produced most of this and hidden all of
it in a diff nobody reads.

This is deliberately NOT a transcription of the DDL in the specification the requirements
folder was written from. That DDL predates the decision to run every model locally: it
carries a 1536-dimension vector column and a `vendor_accounts` table for provider keys.
Neither belongs here.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None

EMBED_DIM = 384


def _uuid() -> sa.types.TypeEngine:
    return postgresql.UUID(as_uuid=True)


def _created() -> sa.Column:
    return sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()"))


def upgrade() -> None:
    # pgvector lives in the migration rather than in a setup script somebody has to
    # remember. A fresh database has to come up with one command.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ------------------------------------------------------------------ accounts

    op.create_table(
        "users",
        sa.Column("id", _uuid(), primary_key=True),
        sa.Column("email", sa.Text(), nullable=False, unique=True),
        sa.Column("display_name", sa.Text()),
        sa.Column("password_hash", sa.Text()),
        _created(),
        sa.Column("deleted_at", sa.DateTime(timezone=True)),
    )

    op.create_table(
        "workspaces",
        sa.Column("id", _uuid(), primary_key=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("owner_user_id", _uuid(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        _created(),
    )

    op.create_table(
        "api_keys",
        sa.Column("id", _uuid(), primary_key=True),
        sa.Column("user_id", _uuid(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("workspace_id", _uuid(), sa.ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        # The key itself is shown once and never stored.
        sa.Column("key_hash", sa.Text(), nullable=False, unique=True),
        sa.Column("prefix", sa.String(16), nullable=False),
        sa.Column("scopes", postgresql.ARRAY(sa.Text()), nullable=False,
                  server_default=sa.text("'{ingest,read,mcp}'::text[]")),
        sa.Column("last_used_at", sa.DateTime(timezone=True)),
        sa.Column("revoked_at", sa.DateTime(timezone=True)),
        _created(),
    )

    # ------------------------------------------------------------------ the corpus

    # current_brief_version_id is circular with brief_versions.project_id, so the column is
    # created here and the constraint after both tables exist.
    op.create_table(
        "projects",
        sa.Column("id", _uuid(), primary_key=True),
        sa.Column("workspace_id", _uuid(), sa.ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text()),
        sa.Column("is_default", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("brief_budget_tokens", sa.Integer(), nullable=False, server_default=sa.text("3000")),
        sa.Column("session_tail_tokens", sa.Integer(), nullable=False, server_default=sa.text("1200")),
        sa.Column("derive_cursor", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("tokens_since_derive", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("last_derived_at", sa.DateTime(timezone=True)),
        sa.Column("current_brief_version_id", _uuid()),
        _created(),
        sa.UniqueConstraint("workspace_id", "name", name="uq_projects_workspace_name"),
    )

    op.create_table(
        "conversations",
        sa.Column("id", _uuid(), primary_key=True),
        sa.Column("project_id", _uuid(), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False),
        sa.Column("vendor", sa.Text(), nullable=False),
        sa.Column("vendor_conv_id", sa.Text()),
        sa.Column("title", sa.Text()),
        sa.Column("model_hint", sa.Text()),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("message_count", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("token_count", sa.Integer(), nullable=False, server_default=sa.text("0")),
        # NULL vendor_conv_id never collides, so two pasted transcripts are two
        # conversations - and the message hash then catches the duplicate turns inside.
        sa.UniqueConstraint("vendor", "vendor_conv_id", name="uq_conversations_vendor_id"),
    )
    op.execute(
        "CREATE INDEX ix_conversations_project_last_seen "
        "ON conversations (project_id, last_seen_at DESC)"
    )

    op.create_table(
        "messages",
        sa.Column("id", _uuid(), primary_key=True),
        sa.Column("conversation_id", _uuid(), sa.ForeignKey("conversations.id", ondelete="CASCADE"), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("client_position", sa.Integer()),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        _created(),
        # Idempotent ingest. The extension re-sends the same turn routinely.
        sa.UniqueConstraint("conversation_id", "content_hash", name="uq_messages_conv_hash"),
        # Ordering.
        sa.UniqueConstraint("conversation_id", "seq", name="uq_messages_conv_seq"),
    )
    op.create_index("ix_messages_conv_seq", "messages", ["conversation_id", "seq"])

    # ------------------------------------------------------------------ the memory

    op.create_table(
        "entries",
        sa.Column("id", _uuid(), primary_key=True),
        sa.Column("project_id", _uuid(), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False),
        sa.Column("layer", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False, server_default=sa.text("'active'")),
        sa.Column("source", sa.Text(), nullable=False, server_default=sa.text("'derived'")),
        sa.Column("current_revision", sa.Integer(), nullable=False, server_default=sa.text("1")),
        sa.Column("confidence", sa.Float(), nullable=False, server_default=sa.text("0.5")),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("seen_in_conversations", sa.Integer(), nullable=False, server_default=sa.text("1")),
        sa.Column("superseded_by", _uuid(), sa.ForeignKey("entries.id")),
        sa.Column("promotion_suggested", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("transmission_failed", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("embedding", Vector(EMBED_DIM)),
        _created(),
        sa.CheckConstraint("layer in ('stable','project','session')", name="ck_entries_layer"),
        sa.CheckConstraint(
            "status in ('active','pinned','removed','superseded','archived')", name="ck_entries_status"
        ),
        sa.CheckConstraint("source in ('derived','user')", name="ck_entries_source"),
    )
    op.create_index("ix_entries_project_status_layer", "entries", ["project_id", "status", "layer"])
    op.execute(
        "CREATE INDEX ix_entries_embedding_hnsw ON entries "
        "USING hnsw (embedding vector_cosine_ops)"
    )

    op.create_table(
        "entry_revisions",
        sa.Column("entry_id", _uuid(), sa.ForeignKey("entries.id", ondelete="CASCADE"), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("changed_by", sa.Text(), nullable=False),
        sa.Column("change_reason", sa.Text()),
        _created(),
        sa.PrimaryKeyConstraint("entry_id", "revision", name="pk_entry_revisions"),
    )

    # Two columns, and the reason the whole project is defensible.
    op.create_table(
        "entry_lineage",
        sa.Column("entry_id", _uuid(), sa.ForeignKey("entries.id", ondelete="CASCADE"), nullable=False),
        sa.Column("message_id", _uuid(), sa.ForeignKey("messages.id", ondelete="CASCADE"), nullable=False),
        sa.PrimaryKeyConstraint("entry_id", "message_id", name="pk_entry_lineage"),
    )

    op.create_table(
        "entry_events",
        sa.Column("id", _uuid(), primary_key=True),
        sa.Column("entry_id", _uuid(), sa.ForeignKey("entries.id", ondelete="CASCADE"), nullable=False),
        sa.Column("user_id", _uuid(), sa.ForeignKey("users.id")),
        sa.Column("event", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB()),
        _created(),
    )

    # ------------------------------------------------------------------ serving

    op.create_table(
        "brief_versions",
        sa.Column("id", _uuid(), primary_key=True),
        sa.Column("project_id", _uuid(), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("rendered_text", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("budget_tokens", sa.Integer(), nullable=False),
        sa.Column("included_entry_ids", postgresql.ARRAY(_uuid()), nullable=False),
        # What did not fit. Where the `excluded` probes come from.
        sa.Column("excluded_entry_ids", postgresql.ARRAY(_uuid()), nullable=False),
        sa.Column("source_message_count", sa.Integer(), nullable=False),
        sa.Column("source_token_count", sa.Integer(), nullable=False),
        sa.Column("trigger", sa.Text(), nullable=False),
        _created(),
        sa.UniqueConstraint("project_id", "version", name="uq_brief_versions_project_version"),
    )

    op.create_foreign_key(
        "fk_projects_current_brief", "projects", "brief_versions", ["current_brief_version_id"], ["id"]
    )

    op.create_table(
        "injections",
        sa.Column("id", _uuid(), primary_key=True),
        sa.Column("brief_version_id", _uuid(), sa.ForeignKey("brief_versions.id", ondelete="CASCADE"), nullable=False),
        sa.Column("door", sa.Text(), nullable=False),
        sa.Column("target_vendor", sa.Text()),
        sa.Column("target_conversation_id", _uuid(), sa.ForeignKey("conversations.id")),
        sa.Column("pack_text", sa.Text(), nullable=False),
        _created(),
    )

    # ------------------------------------------------------------------ measurement

    op.create_table(
        "probes",
        sa.Column("id", _uuid(), primary_key=True),
        sa.Column("project_id", _uuid(), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False),
        # Null for an uncovered probe - raw material no entry claims, which is the only way
        # to measure what extraction missed.
        sa.Column("entry_id", _uuid(), sa.ForeignKey("entries.id", ondelete="CASCADE")),
        sa.Column("entry_revision", sa.Integer()),
        sa.Column("message_id", _uuid(), sa.ForeignKey("messages.id", ondelete="CASCADE")),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("expected_answer", sa.Text(), nullable=False),
        _created(),
        sa.CheckConstraint("category in ('included','excluded','uncovered')", name="ck_probes_category"),
    )

    op.create_table(
        "checkpoints",
        sa.Column("id", _uuid(), primary_key=True),
        sa.Column("injection_id", _uuid(), sa.ForeignKey("injections.id", ondelete="CASCADE"), nullable=False),
        sa.Column("mode", sa.Text(), nullable=False),
        sa.Column("judge_model", sa.Text(), nullable=False),
        sa.Column("answer_model", sa.Text()),
        sa.Column("integrity", sa.Float(), nullable=False),
        sa.Column("probe_count", sa.Integer(), nullable=False),
        _created(),
        sa.CheckConstraint("mode in ('local','in_chat')", name="ck_checkpoints_mode"),
    )

    op.create_table(
        "probe_results",
        sa.Column("checkpoint_id", _uuid(), sa.ForeignKey("checkpoints.id", ondelete="CASCADE"), nullable=False),
        sa.Column("probe_id", _uuid(), sa.ForeignKey("probes.id", ondelete="CASCADE"), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("judge_reason", sa.Text()),
        sa.PrimaryKeyConstraint("checkpoint_id", "probe_id", name="pk_probe_results"),
        # Exactly three values, enforced. A judge that could emit 0.73 would be inventing a
        # precision the instrument does not have.
        sa.CheckConstraint("score in (0, 0.5, 1)", name="ck_probe_results_score"),
    )

    op.create_table(
        "suggestions",
        sa.Column("id", _uuid(), primary_key=True),
        sa.Column("project_id", _uuid(), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("entry_id", _uuid(), sa.ForeignKey("entries.id")),
        sa.Column("message_id", _uuid(), sa.ForeignKey("messages.id")),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False, server_default=sa.text("'open'")),
        _created(),
    )

    # ------------------------------------------------------------------ machinery

    op.create_table(
        "jobs",
        sa.Column("id", _uuid(), primary_key=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False, server_default=sa.text("'queued'")),
        sa.Column("attempts", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("run_after", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("locked_by", sa.Text()),
        sa.Column("locked_at", sa.DateTime(timezone=True)),
        sa.Column("error", sa.Text()),
        _created(),
    )
    op.create_index("ix_jobs_status_run_after", "jobs", ["status", "run_after"])
    # One derive per project, enforced by the database. Two of them would extract the same
    # messages twice and merge each other's output. Application-level debouncing mostly
    # works; this cannot be got wrong under load.
    op.execute(
        "CREATE UNIQUE INDEX one_derive_per_project ON jobs ((payload->>'project_id')) "
        "WHERE kind = 'derive' AND status IN ('queued','running')"
    )

    op.create_table(
        "model_calls",
        sa.Column("id", _uuid(), primary_key=True),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        # Which of the three extractors produced this. Without it, comparing them is
        # impossible and every number in the harness is unattributable.
        sa.Column("implementation", sa.Text()),
        sa.Column("prompt_version", sa.Text()),
        sa.Column("input_tokens", sa.Integer()),
        sa.Column("output_tokens", sa.Integer()),
        sa.Column("latency_ms", sa.Integer()),
        sa.Column("validated_first_try", sa.Boolean()),
        sa.Column("raw_output", sa.Text()),
        sa.Column("error", sa.Text()),
        _created(),
    )


def downgrade() -> None:
    op.drop_table("model_calls")
    op.execute("DROP INDEX IF EXISTS one_derive_per_project")
    op.drop_index("ix_jobs_status_run_after", table_name="jobs")
    op.drop_table("jobs")
    op.drop_table("suggestions")
    op.drop_table("probe_results")
    op.drop_table("checkpoints")
    op.drop_table("probes")
    op.drop_table("injections")
    op.drop_constraint("fk_projects_current_brief", "projects", type_="foreignkey")
    op.drop_table("brief_versions")
    op.drop_table("entry_events")
    op.drop_table("entry_lineage")
    op.drop_table("entry_revisions")
    op.execute("DROP INDEX IF EXISTS ix_entries_embedding_hnsw")
    op.drop_index("ix_entries_project_status_layer", table_name="entries")
    op.drop_table("entries")
    op.drop_index("ix_messages_conv_seq", table_name="messages")
    op.drop_table("messages")
    op.execute("DROP INDEX IF EXISTS ix_conversations_project_last_seen")
    op.drop_table("conversations")
    op.drop_table("projects")
    op.drop_table("api_keys")
    op.drop_table("workspaces")
    op.drop_table("users")
