"""Owners, listings, and each listing's history.

Hand-written rather than autogenerated, so the constraints that carry the design are
visible here: the vocabularies as CHECKs built from the same tuples the code uses, the
coordinate ranges, a phone number that is required because calling it is the point, and
cascade deletes so that withdrawing a listing really removes its history with it.

No distance index yet. The map's bounding-box query is fine without one at demo scale, and
the GiST index on ll_to_earth() arrives in stage 4 with the query that needs it.

Revision ID: 0002_listings
Revises: 0001_extensions
Create Date: 2026-10-07
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# The vocabularies as they were when this migration was written. Copied, not imported from
# roamer.models: a migration that imports its values changes meaning whenever the model
# does, and an old migration has to keep meaning what it meant. tests/test_schema.py fails
# when the two drift apart, which is the cue to write a new migration.
SOURCES = ("owner", "import")
STATUSES = ("pending_verification", "awaiting_approval", "lost", "reunited")
SPECIES = ("dog", "cat", "other")
SEXES = ("male", "female", "unknown")
SIZES = ("small", "medium", "large")
PRECISIONS = ("exact", "approximate")
EVENT_KINDS = (
    "created",
    "verified",
    "approved",
    "edited",
    "photo_removed",
    "confirmed",
    "reunited",
    "reopened",
    "hidden",
    "unhidden",
    "claimed",
)
ACTORS = ("owner", "admin", "system")

revision: str = "0002_listings"
down_revision: Union[str, None] = "0001_extensions"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _in(column: str, values: tuple[str, ...]) -> str:
    quoted = ", ".join(f"'{value}'" for value in values)
    return f"{column} IN ({quoted})"


def upgrade() -> None:
    op.create_table(
        "owners",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("email", postgresql.CITEXT(), nullable=False, unique=True),
        sa.Column("email_confirmed_at", sa.DateTime(timezone=True)),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
    )

    op.create_table(
        "listings",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("code", sa.Text(), nullable=False, unique=True),
        sa.Column(
            "owner_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("owners.id", ondelete="CASCADE"),
        ),
        sa.Column("source", sa.Text(), nullable=False, server_default="owner"),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("species", sa.Text(), nullable=False),
        sa.Column("name", sa.Text()),
        sa.Column("sex", sa.Text(), nullable=False, server_default="unknown"),
        sa.Column("breed", sa.Text()),
        sa.Column("colours", sa.Text()),
        sa.Column("size", sa.Text()),
        sa.Column("age_text", sa.Text()),
        sa.Column("description", sa.Text()),
        sa.Column("approach_advice", sa.Text()),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_lat", sa.Float(), nullable=False),
        sa.Column("last_seen_lng", sa.Float(), nullable=False),
        sa.Column("location_precision", sa.Text(), nullable=False, server_default="exact"),
        sa.Column("area_label", sa.Text()),
        sa.Column("contact_name", sa.Text()),
        sa.Column("contact_phone", sa.Text(), nullable=False),
        sa.Column("show_phone", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("last_confirmed_at", sa.DateTime(timezone=True)),
        sa.Column("hidden_at", sa.DateTime(timezone=True)),
        sa.Column("hidden_reason", sa.Text()),
        sa.Column("seeded", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.CheckConstraint(_in("source", SOURCES), name="listings_source"),
        sa.CheckConstraint(_in("status", STATUSES), name="listings_status"),
        sa.CheckConstraint(_in("species", SPECIES), name="listings_species"),
        sa.CheckConstraint(_in("sex", SEXES), name="listings_sex"),
        sa.CheckConstraint(f"size IS NULL OR {_in('size', SIZES)}", name="listings_size"),
        sa.CheckConstraint(
            _in("location_precision", PRECISIONS), name="listings_location_precision"
        ),
        sa.CheckConstraint("last_seen_lat BETWEEN -90 AND 90", name="listings_lat"),
        sa.CheckConstraint("last_seen_lng BETWEEN -180 AND 180", name="listings_lng"),
        # An owner listing always has an owner. Only an unclaimed import (later) has none.
        sa.CheckConstraint(
            "source = 'import' OR owner_id IS NOT NULL", name="listings_owner_required"
        ),
        # A hidden listing always says why.
        sa.CheckConstraint(
            "hidden_at IS NULL OR hidden_reason IS NOT NULL", name="listings_hidden_reason"
        ),
    )
    # The map asks one question: active listings, in a box, newest first. Until stage 4's
    # distance index exists, this partial index is what keeps that cheap.
    op.create_index(
        "listings_active_last_seen",
        "listings",
        ["last_seen_at"],
        postgresql_where=sa.text("status = 'lost' AND hidden_at IS NULL"),
    )
    op.create_index("listings_owner_id", "listings", ["owner_id"])

    op.create_table(
        "listing_events",
        sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column(
            "listing_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("listings.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("actor", sa.Text(), nullable=False),
        sa.Column(
            "detail",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.CheckConstraint(_in("kind", EVENT_KINDS), name="listing_events_kind"),
        sa.CheckConstraint(_in("actor", ACTORS), name="listing_events_actor"),
    )
    op.create_index("listing_events_listing_id", "listing_events", ["listing_id", "id"])


def downgrade() -> None:
    op.drop_table("listing_events")
    op.drop_table("listings")
    op.drop_table("owners")
