"""Comparing an extractor against the corpus, in one place.

This module holds the field-by-field comparison and the arithmetic self-check. It exists so
there is exactly one implementation of "did this extractor get this document right", used
both by `tests/test_corpus.py` and by the extractor comparison below. Two copies would drift,
and the copy that drifted would be the one reporting the numbers - which is the same argument
this project made for the harness driving the real pipeline rather than reimplementing it.

Run the comparison with:

    python -m mailman.corpus_check

It reports every available extractor against all eleven documents. The trained extractor is
included when its weights are on disk and skipped, loudly, when they are not - they are 250MB
and gitignored, so a fresh checkout has the heuristic only.

**This is not the stage 8 harness.** That one measures thirty to forty documents, records a
baseline into the repository and keeps run history. This answers one question that has been
outstanding since stage 3: on the same eleven documents, does the trained model beat the
regular expressions? The heuristic is what deploys, so a 250MB model that cannot beat it is
not worth shipping, and that comparison decides whether the model is a feature or a footnote.
"""

from __future__ import annotations

import io
import time
from decimal import Decimal
from pathlib import Path
from typing import Any

from mailman.corpus import CASES, Case
from mailman.invoice import InvoiceFields

# Fields one extractor is known not to reach, exempted for it and ignored by the extractor
# comparison - a gap is one component's limitation, not a hole in the answer key.
#
# **Empty since stage 9.** It held `buyer_name` on every document for eight stages, on the
# stated grounds that "no rule finds a buyer reliably". Attempt 3 tested that claim instead of
# repeating it: a rule reading the text after a buyer label gets 33 of 34, beating the trained
# model's 30, which truncates multi-word names. The claim had never been measured.
#
# `test_known_gaps_are_still_gaps` is what forced this to be emptied rather than left - an
# exemption that outlives its reason is a permanently suppressed failure.
KNOWN_GAPS: set[tuple[str, str]] = set()

# How each key in a case's `expected` block is turned into an actual value. Anything not in
# here is a label nobody has said how to measure, and the caller fails on it rather than
# passing over it. `has_negative_line`, `issue_date_is_ambiguous` and `spans_pages` sat in
# the labels for three sessions naming nothing on `InvoiceFields`, so every comparison
# silently skipped them - including the only assertion that `06-ambiguous-date` flags its
# date rather than guessing, which is the entire reason that document is in the corpus.
CHECKS: dict[str, Any] = {
    "invoice_number": lambda f, pages: f.invoice_number,
    "vendor_name": lambda f, pages: f.vendor_name,
    "buyer_name": lambda f, pages: f.buyer_name,
    "currency": lambda f, pages: f.currency,
    # Dates in ISO form, so the label reads like the document's answer.
    "issue_date": lambda f, pages: f.issue_date.isoformat() if f.issue_date else None,
    "due_date": lambda f, pages: f.due_date.isoformat() if f.due_date else None,
    # Amounts compared numerically: "270.40" and Decimal("270.4") are the same answer.
    "subtotal": lambda f, pages: f.subtotal,
    "tax": lambda f, pages: f.tax,
    "total": lambda f, pages: f.total,
    "line_items": lambda f, pages: f.line_items,
    "line_item_count": lambda f, pages: len(f.line_items),
    "has_negative_line": lambda f, pages: any(
        item["amount"] is not None and item["amount"] < 0 for item in f.line_items
    ),
    "issue_date_is_ambiguous": lambda f, pages: "issue_date" in f.ambiguous_dates,
    "spans_pages": lambda f, pages: pages > 1,
}

MONEY_KEYS = {"subtotal", "tax", "total"}
LINE_MONEY_KEYS = {"quantity", "unit_price", "amount"}


def _money(value: Any) -> Decimal | None:
    return None if value is None else Decimal(str(value))


def document_text(case: Case) -> tuple[str, int]:
    """The document as the pipeline sees it: pdfplumber over the generated bytes."""
    import pdfplumber

    with pdfplumber.open(io.BytesIO(case.pdf())) as document:
        pages = [page.extract_text() or "" for page in document.pages]
    return "\n".join(pages), len(pages)


def unknown_keys(cases: list[Case] = CASES) -> list[str]:
    """Expected keys with no entry in CHECKS. A label nothing evaluates is not an assertion."""
    return sorted(
        f"{case.name}.{key}"
        for case in cases
        for key in case.expected
        if key not in CHECKS
    )


def line_item_problems(expected: list[dict], actual: list[dict]) -> list[str]:
    """Per line, per field. A length check alone is `line_item_count` wearing a disguise."""
    if len(expected) != len(actual):
        return [
            f"line_items: expected {len(expected)} lines, got {len(actual)}: "
            + ", ".join(repr(item["description"]) for item in actual)
        ]

    problems: list[str] = []
    for index, (want, got) in enumerate(zip(expected, actual)):
        for key, value in want.items():
            found = got.get(key)
            same = (
                _money(value) == _money(found)
                if key in LINE_MONEY_KEYS
                else value == found
            )
            if not same:
                problems.append(f"line[{index}].{key}: expected {value!r}, got {found!r}")
    return problems


def field_results(
    case: Case, fields: InvoiceFields, page_count: int, *, apply_known_gaps: bool = True
) -> dict[str, bool]:
    """Per expected key: did this extractor get it right.

    Returns a mapping rather than a list of strings, because the comparison below needs to
    count fields and the test needs to print them, and deriving one from the other is how the
    two drift apart.
    """
    results: dict[str, bool] = {}
    for key, expected in case.expected.items():
        if apply_known_gaps and (case.name, key) in KNOWN_GAPS:
            continue
        if key == "line_items":
            results[key] = not line_item_problems(expected, fields.line_items)
            continue
        actual = CHECKS[key](fields, page_count)
        if key in MONEY_KEYS:
            results[key] = _money(expected) == _money(actual)
        else:
            results[key] = expected == actual
    return results


def field_problems(
    case: Case, fields: InvoiceFields, page_count: int, *, apply_known_gaps: bool = True
) -> list[str]:
    """The same comparison, rendered for a human or a failing assertion."""
    problems: list[str] = []
    for key, expected in case.expected.items():
        if apply_known_gaps and (case.name, key) in KNOWN_GAPS:
            continue
        if key == "line_items":
            problems.extend(line_item_problems(expected, fields.line_items))
            continue
        actual = CHECKS[key](fields, page_count)
        wrong = (
            _money(expected) != _money(actual)
            if key in MONEY_KEYS
            else expected != actual
        )
        if wrong:
            problems.append(f"{key}: expected {expected!r}, got {actual!r}")
    return problems


def arithmetic_problems(fields: InvoiceFields) -> list[str]:
    """Each document against its own arithmetic. No labels involved.

    This is the check that needs nothing to be right about the answer key, so it survives a
    label that is wrong and a document that contradicts itself. Both have happened here, and
    this is what found them.
    """
    lines = fields.line_items
    subtotal, tax, total = fields.subtotal, fields.tax, fields.total
    wrong: list[str] = []

    for item in lines:
        quantity, unit_price, amount = item["quantity"], item["unit_price"], item["amount"]
        if None not in (quantity, unit_price, amount) and quantity * unit_price != amount:
            wrong.append(
                f"line[{item['line_no']}] {item['description']!r}: "
                f"{quantity} x {unit_price} = {quantity * unit_price}, printed {amount}"
            )

    if lines and subtotal is not None:
        summed = sum((i["amount"] for i in lines if i["amount"] is not None), Decimal(0))
        if summed != subtotal:
            wrong.append(
                f"{len(lines)} line items sum to {summed}, subtotal says {subtotal} "
                f"(difference {subtotal - summed}) - a line is missing, invented or misread"
            )

    if None not in (subtotal, tax, total) and subtotal + tax != total:
        wrong.append(f"subtotal {subtotal} + tax {tax} = {subtotal + tax}, total says {total}")

    return wrong


# --------------------------------------------------------------------------------------
# The comparison: every available extractor, over all eleven documents.
# --------------------------------------------------------------------------------------


class Outcome:
    """What one extractor did with one document."""

    def __init__(self, case: Case) -> None:
        self.case = case
        self.fields: InvoiceFields | None = None
        # What a refused extraction still managed to read. Scored, and reported separately
        # from a clean extraction, because "it got nine fields right and then refused over
        # the tenth" and "it got nothing" are different findings.
        self.partial: InvoiceFields | None = None
        self.refused: str | None = None
        self.latency_ms: int = 0
        self.results: dict[str, bool] = {}
        self.problems: list[str] = []
        self.arithmetic: list[str] = []

    @property
    def clean(self) -> bool:
        if self.case.should_fail:
            return self.refused is not None
        return self.fields is not None and not self.problems


def run_case(case: Case, extractor, text: str, page_count: int) -> Outcome:
    from mailman.extractor import ExtractionError

    outcome = Outcome(case)
    started = time.monotonic()
    try:
        outcome.fields = extractor.extract(text).fields
    except ExtractionError as exc:
        outcome.refused = str(exc)
        # A refusal must not hide what the extractor did manage to read. The error carries
        # the partial `InvoiceRead` for exactly this reason - "a failure with no evidence
        # cannot be investigated" is why it is stored on the row in the first place - and
        # without rebuilding it here the comparison reports eleven blank columns and says
        # nothing about WHICH field caused the refusal or how much else was right.
        raw = (exc.raw or {}).get("read") if isinstance(exc.raw, dict) else None
        if isinstance(raw, dict):
            try:
                from mailman.invoice import InvoiceRead

                outcome.partial = InvoiceFields(InvoiceRead(**raw))
            except Exception:                     # noqa: BLE001 - best effort, never fatal
                outcome.partial = None
    outcome.latency_ms = int((time.monotonic() - started) * 1000)

    scored = outcome.fields if outcome.fields is not None else outcome.partial
    if scored is not None:
        # apply_known_gaps=False: a gap is one extractor's limitation, and
        # suppressing the field here would hide the only one they differ on.
        outcome.results = field_results(case, scored, page_count, apply_known_gaps=False)
        outcome.problems = field_problems(case, scored, page_count, apply_known_gaps=False)
        outcome.arithmetic = arithmetic_problems(scored)
    return outcome


def available_extractors(model_dir: str = "./models/extractor") -> list[tuple[str, Any, str]]:
    """Every extractor that can actually run here, with a note on what it is.

    The trained one is skipped loudly rather than silently: its weights are 250MB and
    gitignored, so a fresh checkout has the heuristic only, and a comparison that quietly
    reported one extractor would look like a comparison.
    """
    from mailman.heuristic import HeuristicExtractor

    found: list[tuple[str, Any, str]] = [
        ("heuristic", HeuristicExtractor(), "regex and layout rules, no weights, deploys")
    ]

    try:
        from mailman.hybrid import HybridExtractor

        hybrid = HybridExtractor(model_dir=model_dir)
        if hybrid.trained is not None:
            found.append(
                ("hybrid", hybrid, f"heuristic + {', '.join(hybrid.model_fields)} from the model")
            )
    except Exception as exc:                      # noqa: BLE001
        print(f"  hybrid extractor unavailable: {type(exc).__name__}: {exc}")

    try:
        from mailman.trained import TrainedExtractor

        trained = TrainedExtractor(model_dir=model_dir)
        trained._load()
        manifest = trained.manifest or {}
        note = (
            f"DistilBERT, shifted {manifest.get('serving_shifted', '?')}, "
            f"trained {str(manifest.get('trained_at', '?'))[:10]}"
        )
        found.append(("trained", trained, note))
    except Exception as exc:                      # noqa: BLE001 - reported, not swallowed
        print(f"  trained extractor unavailable: {type(exc).__name__}: {exc}")
        print("  (weights are gitignored; train one with notebooks/train_extractor.ipynb)")
        print()

    return found


def main(model_dir: str = "./models/extractor") -> int:
    stray = unknown_keys()
    if stray:
        print(f"expected keys with no entry in CHECKS: {stray}")
        return 1

    print("corpus check - every available extractor against all eleven documents")
    print()
    extractors = available_extractors(model_dir)

    documents = [(case, *document_text(case)) for case in CASES]
    outcomes: dict[str, list[Outcome]] = {}
    for name, extractor, note in extractors:
        print(f"  {name:10} {note}")
        outcomes[name] = [run_case(c, extractor, t, p) for c, t, p in documents]
    print()

    names = [n for n, _, _ in extractors]
    width = max(len(n) for n in names)

    print("=" * 78)
    print("PER DOCUMENT")
    print("=" * 78)
    header = f"  {'DOCUMENT':32}" + "".join(f"{n:>{width + 12}}" for n in names)
    print(header)
    for index, (case, _, _) in enumerate(documents):
        row = f"  {case.name:32}"
        for name in names:
            o = outcomes[name][index]
            if case.should_fail:
                cell = "refused OK" if o.refused else "EXTRACTED"
            elif o.refused:
                wrong = sum(1 for ok in o.results.values() if not ok)
                cell = f"refused, {wrong} wrong" if o.results else "refused"
            else:
                wrong = sum(1 for ok in o.results.values() if not ok)
                cell = "ok" if not wrong else f"{wrong} wrong"
            row += f"{cell:>{width + 12}}"
        print(row)

    print()
    print("=" * 78)
    print("PER FIELD - documents where the field was labelled and the extractor got it right")
    print("=" * 78)
    fields_seen: list[str] = []
    for case in CASES:
        for key in case.expected:
            if key not in fields_seen:
                fields_seen.append(key)

    print(f"  {'FIELD':26}" + "".join(f"{n:>{width + 12}}" for n in names))
    for key in fields_seen:
        row = f"  {key:26}"
        for name in names:
            ok = sum(1 for o in outcomes[name] if o.results.get(key) is True)
            seen = sum(1 for o in outcomes[name] if key in o.results)
            cell = f"{ok}/{seen}" if seen else "-"
            row += f"{cell:>{width + 12}}"
        print(row)

    print()
    print("=" * 78)
    print("SUMMARY")
    print("=" * 78)
    print(f"  {'':26}" + "".join(f"{n:>{width + 12}}" for n in names))
    rows = {
        "documents clean": lambda os_: f"{sum(o.clean for o in os_)}/{len(os_)}",
        "fields right if refusal ignored": lambda os_: (
            f"{sum(sum(o.results.values()) for o in os_)}"
            f"/{sum(len(o.results) for o in os_)}"
        ),
        "arithmetic breaks": lambda os_: str(sum(1 for o in os_ if o.arithmetic)),
        "refused to extract": lambda os_: str(sum(1 for o in os_ if o.refused)),
        "total latency (ms)": lambda os_: str(sum(o.latency_ms for o in os_)),
    }
    for label, fn in rows.items():
        print(f"  {label:26}" + "".join(f"{fn(outcomes[n]):>{width + 12}}" for n in names))

    print()
    print("What decides whether the model ships: the heuristic is what deploys - no weights,")
    print("no GPU, no 250MB download. A trained model has to beat it on these documents to be")
    print("worth carrying, and 'it did not' is a result worth reporting either way.")

    for name in names:
        wrong = [o for o in outcomes[name] if not o.clean and not o.case.should_fail]
        if not wrong:
            continue
        print()
        print(f"--- {name}: what it got wrong ---")
        for o in wrong:
            print(f"  {o.case.name}")
            for p in (o.problems or [f"refused: {o.refused}"])[:6]:
                print(f"      {p}")
            for a in o.arithmetic[:3]:
                print(f"      arithmetic: {a}")
    return 0


if __name__ == "__main__":
    import sys

    raise SystemExit(main(sys.argv[1] if len(sys.argv) > 1 else "./models/extractor"))
